#!/bin/sh

#formatting
RED_FG=$(tput setaf 1)
NC=$(tput sgr0)


if [ $# -eq "0" ]; then
	echo $RED_FG'
   /$$                                                                  /$$     
  | $$                                                                 | $$     
  | $$$$$$$   /$$$$$$  /$$   /$$ /$$  /$$  /$$  /$$$$$$   /$$$$$$  /$$$$$$$
  | $$__  $$ /$$__  $$|  $$ /$$/| $$ | $$ | $$ /$$__  $$ /$$__  $$/$$__  $$
  | $$  \ $$| $$$$$$$$ \  $$$$/ | $$ | $$ | $$| $$  \ $$| $$  \__/ $$  | $$
  | $$  | $$| $$_____/  >$$  $$ | $$ | $$ | $$| $$  | $$| $$     | $$  | $$
  | $$  | $$|  $$$$$$$ /$$/\  $$|  $$$$$/$$$$/|  $$$$$$/| $$     |  $$$$$$$
  |__/  |__/ \_______/|__/  \__/ \_____/\___/  \______/ |__/      \_______/'$NC
	echo "             create strings of hex compopsed of words
usage:
  PIPES: stdout source | ./hexword [filter] arg1 arg2 ... argn
  TEXT : ./hexword filename filter arg1 arg2 ... argn
    arg#=integer wordlength 	filename=wordlist* 
    filters: -lo		hex letters only, words with ABCDEF
*note:	     -ios		-lo plus I=1, O=0, S=5
 filter      -los		-lo plus L=1, O=0, S=5
 optional    -all<default>	-lo plus I,L=1**, O=0, S=5
	*: case insensitive, words delimited by spaces or newline 
	**: words with IL or LI in them are removed to avoid confusion
examples: 
   ./hexword dictionary.txt 8 4				->      B100D13DFACE
   echo \"BEEF FOOD FIASCO DEEDED\" | ./hexword -lo 4 6	->      BEEFDEEDED"
	exit
fi

WORD=""
LETTERS_ONLY='[A-F]'
I_O_S='[A-FIOS]'
L_O_S='[A-FLOS]'
ALL='[A-FILOS]'
METHOD=$ALL

get_word ()
{
	WORD="$WORD $(echo "$INPUT" | grep "\<.\{$LETTERS\}\>" | shuf -n 1 )"
} 

[ -f "$1" ] && INPUT="$(cat $1)" || INPUT="$(cat -)"
#narrow input
INPUT="$(echo "$INPUT" | sed -e 's/ /\n/g' -e 's/.*/\U&/' | grep "\<$METHOD*\>" | grep -v 'IL' | grep -v 'LI')"

for ARG in "$@"
do
	if [ "$ARG" = "-lo" ] ; then
		METHOD=$LETTERS_ONLY
		INPUT=$(echo "$INPUT" | grep "\<$METHOD*\>")
	elif [ "$ARG" = "-ios" ] ; then
		METHOD=$I_O_S
		INPUT=$(echo "$INPUT" | grep "\<$METHOD*\>")
	elif [ "$ARG" = "-los" ] ; then
		METHOD=$L_O_S
		INPUT=$(echo "$INPUT" | grep "\<$METHOD*\>")
	elif [ "$ARG" = "-a" ] ; then
		METHOD=$ALL
		INPUT=$(echo "$INPUT" | grep "\<$METHOD*\>")
	elif [ ! -f $ARG ] ; then 
		LETTERS="$ARG"
		get_word
	fi

done
echo $(echo "$WORD" | sed -e 's/I/1/g' -e 's/O/0/g' -e 's/S/5/g' -e 's/L/1/g')
